//! M1 4-week checkpoint — 50-spec scenario gate (PLAN.md §10).
//!
//! Replays realistic completion scenarios against the *converted* spec
//! cache (`tests/fixtures/converted/`, produced by `tools/ts-to-json`)
//! to prove the `complete` pipeline still resolves common subcommands
//! across the top real-world tools. This is the headline acceptance
//! criterion for the M1 4-week checkpoint (CLAUDE.md §7.3).
//!
//! The converted cache is `.gitignore`d (it is large and regenerated by
//! `bun run convert:all`), so this test **skips gracefully** when the
//! directory is absent — it is a local acceptance gate, not a CI gate.
//! Regenerate with:
//!     cd tools/ts-to-json && bun run convert:all
//!
//! Each scenario asserts that a known subcommand shows up in the ranked
//! completion list for a partial command line. Subcommands are Tier-A
//! (static) data, so they are the most stable thing to lock down.
//!
//! Refs: PLAN.md §10 (M1 4주차), CLAUDE.md §7.3

use nerv_engine::{SpecRegistry, complete};
use std::path::PathBuf;

fn converted_dir() -> PathBuf {
    [env!("CARGO_MANIFEST_DIR"), "tests", "fixtures", "converted"]
        .iter()
        .collect()
}

/// The converted cache is real only if it holds spec files. The directory
/// itself exists on every checkout (it carries a tracked `.gitignore`), so
/// `is_dir()` alone would make CI load an empty registry and fail all 54
/// scenarios instead of skipping.
fn has_converted_specs(dir: &PathBuf) -> bool {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return false;
    };
    entries.filter_map(Result::ok).any(|e| {
        let name = e.file_name();
        let name = name.to_string_lossy();
        name.ends_with(".json") || name.ends_with(".json.gz")
    })
}

/// (command line typed so far, subcommand insertion expected in result).
/// Cursor is always end-of-line.
const SCENARIOS: &[(&str, &str)] = &[
    // git (10)
    ("git che", "checkout"),
    ("git sta", "status"),
    ("git com", "commit"),
    ("git bra", "branch"),
    ("git reb", "rebase"),
    ("git pus", "push"),
    ("git pul", "pull"),
    ("git clo", "clone"),
    ("git fe", "fetch"),
    ("git ta", "tag"),
    // docker (6)
    ("docker ru", "run"),
    ("docker bui", "build"),
    ("docker pul", "pull"),
    ("docker pus", "push"),
    ("docker exe", "exec"),
    ("docker sto", "stop"),
    // kubectl (6)
    ("kubectl get", "get"),
    ("kubectl des", "describe"),
    ("kubectl log", "logs"),
    ("kubectl app", "apply"),
    ("kubectl del", "delete"),
    ("kubectl cre", "create"),
    // npm (5)
    ("npm ins", "install"),
    ("npm ru", "run"),
    ("npm pub", "publish"),
    ("npm ini", "init"),
    ("npm te", "test"),
    // cargo (6)
    ("cargo bui", "build"),
    ("cargo te", "test"),
    ("cargo ru", "run"),
    ("cargo che", "check"),
    ("cargo doc", "doc"),
    ("cargo pub", "publish"),
    // gh (4)
    ("gh pr", "pr"),
    ("gh re", "repo"),
    ("gh is", "issue"),
    ("gh au", "auth"),
    // brew (3)
    ("brew ins", "install"),
    ("brew uni", "uninstall"),
    ("brew sea", "search"),
    // go (4)
    ("go bui", "build"),
    ("go te", "test"),
    ("go ru", "run"),
    ("go mod", "mod"),
    // terraform (4)
    ("terraform pl", "plan"),
    ("terraform app", "apply"),
    ("terraform ini", "init"),
    ("terraform des", "destroy"),
    // helm (3)
    ("helm ins", "install"),
    ("helm upg", "upgrade"),
    ("helm ls", "ls"),
    // pip (3)
    ("pip ins", "install"),
    ("pip uni", "uninstall"),
    ("pip li", "list"),
];

#[test]
fn top_spec_subcommand_scenarios() {
    let dir = converted_dir();
    if !has_converted_specs(&dir) {
        eprintln!(
            "[skip] converted spec cache absent at {} — \
             run `cd tools/ts-to-json && bun run convert:all` to enable \
             the 50-spec scenario gate",
            dir.display()
        );
        return;
    }

    let registry = SpecRegistry::at_dir(&dir);
    let mut failures = Vec::new();

    for (line, expected) in SCENARIOS {
        let cursor = line.len();
        let result = complete(line, cursor, &registry);
        let hit = result.items.iter().any(|s| s.insertion == *expected);
        if !hit {
            let top: Vec<&str> = result
                .items
                .iter()
                .take(8)
                .map(|s| s.insertion.as_str())
                .collect();
            failures.push(format!(
                "  `{line}` → expected `{expected}`; got [{}]{}",
                top.join(", "),
                result
                    .reason
                    .as_ref()
                    .map(|r| format!(" (reason: {r})"))
                    .unwrap_or_default()
            ));
        }
    }

    assert!(
        SCENARIOS.len() >= 50,
        "scenario table shrank below the 50-spec checkpoint floor ({})",
        SCENARIOS.len()
    );
    assert!(
        failures.is_empty(),
        "{} / {} scenarios failed:\n{}",
        failures.len(),
        SCENARIOS.len(),
        failures.join("\n")
    );
}
