#!/usr/bin/env bash
# e2e-isolated.sh — reversible nerv smoke test
#
# Spawns a fresh zsh in an isolated $ZDOTDIR (no oh-my-zsh, no Q,
# no plugins, no contact with the user's ~/.zshrc). Builds the
# release binary if missing, starts the daemon, prints the scenario
# checklist, and execs into the test shell. `exit` returns the user
# to their original shell with no state changes.
#
# Usage:
#   ./scripts/e2e-isolated.sh
#
# Optional env:
#   NERV_SKIP_BUILD=1   skip the cargo build step
#   NERV_SKIP_SPECS=1   skip rebuilding the spec cache
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN="$REPO_ROOT/target/release/nerv"
TEST_DIR=/tmp/nerv-test
SPEC_SRC="$REPO_ROOT/crates/nerv-engine/tests/fixtures/converted"
SPEC_DST="$HOME/Library/Caches/nerv/specs"

bold()  { printf '\033[1m%s\033[0m\n' "$*"; }
dim()   { printf '\033[2m%s\033[0m\n' "$*"; }
warn()  { printf '\033[33m%s\033[0m\n' "$*"; }
fail()  { printf '\033[31m%s\033[0m\n' "$*" >&2; exit 1; }

# 1. Build binary if missing.
if [ -z "${NERV_SKIP_BUILD:-}" ]; then
  if [ ! -x "$BIN" ] || [ "$REPO_ROOT/crates/nerv-cli/src/main.rs" -nt "$BIN" ]; then
    bold "[1/5] Building nerv (release) …"
    (cd "$REPO_ROOT" && cargo build --release -p nerv-cli -p nerv-daemon)
  else
    dim "[1/5] Binary already up-to-date — skipping build."
  fi
else
  dim "[1/5] Skipped build (NERV_SKIP_BUILD=1)."
fi
[ -x "$BIN" ] || fail "binary missing after build: $BIN"

# 2. Rebuild spec cache (715 specs, gzip-compressed) if directory empty.
if [ -z "${NERV_SKIP_SPECS:-}" ]; then
  if [ ! -d "$SPEC_DST" ] || [ -z "$(ls -A "$SPEC_DST" 2>/dev/null)" ]; then
    if [ -d "$SPEC_SRC" ]; then
      bold "[2/5] Installing gzipped spec cache to $SPEC_DST …"
      mkdir -p "$SPEC_DST"
      (cd "$REPO_ROOT" && cargo run --release -q -p nerv-engine --bin build-specs -- \
        --input "$SPEC_SRC" \
        --output "$SPEC_DST" \
        --compress)
    else
      warn "[2/5] No converted specs at $SPEC_SRC — only hand-rolled fixtures will load."
      warn "       Run: cd tools/ts-to-json && bun run convert:all"
    fi
  else
    dim "[2/5] Spec cache already populated — skipping rebuild."
  fi
else
  dim "[2/5] Skipped spec install (NERV_SKIP_SPECS=1)."
fi

# 3. Restart daemon so it picks up any new binary / specs.
bold "[3/5] Restarting daemon …"
"$BIN" stop >/dev/null 2>&1 || true
sleep 0.3
"$BIN" start

# 4. Write isolated .zshrc (no plugins, no Q, no oh-my-zsh).
bold "[4/5] Preparing isolated ZDOTDIR at $TEST_DIR …"
mkdir -p "$TEST_DIR"
cat > "$TEST_DIR/.zshrc" <<EOF
# Auto-generated by scripts/e2e-isolated.sh — safe to delete.
PS1=$'%F{green}nerv-test%f %~ %# '
export PATH="$REPO_ROOT/target/release:\$PATH"
eval "\$($BIN init zsh)"
EOF

# 5. Print scenario menu + exec into the isolated shell.
bold "[5/5] Entering isolated zsh. Try:"
cat <<'EOF'

  cd <Tab>            — folder list (filepaths, folders only)
  cd t<Tab>           — folders starting with "t"
  cd <Tab> ↓ ↓ ↓      — arrow cycle (wraps at top/bottom)

  git <Tab>           — subcommands
  git co<Tab>         — prefix match (checkout, commit)
  git commit --<Tab>  — long options only

  yarn <Tab>          — subcommands + package.json scripts (need pkg.json)
  yarn run <Tab>      — only scripts

  z <Tab>             — zsh-z / zoxide history (if ~/.z present)
  z encl<Tab>         — score-sorted match

  Ghost text          — top suggestion appears in dim grey after the
                        cursor; Right-Arrow accepts at end of line.

  Frecency            — repeat-pick the same item; on the next request
                        it floats to the top of the popup.

Exit with `exit` (or close the tab). No changes to your real ~/.zshrc.

EOF

exec env ZDOTDIR="$TEST_DIR" zsh
